import { Toaster } from "react-hot-toast";
import { Inter } from "next/font/google";

import "@appwrite.io/pink";
import "@appwrite.io/pink-icons";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Toaster position="bottom-right" />
      </body>
    </html>
  );
}
